### **The session’s central workflow is:** connect → create a cursor → execute SQL → retrieveresults or save changes

## **Topic 1 — Connecting Python to SQLite**

In [1]:
import sqlite3

In [2]:
connection = sqlite3.connect("Exercise3.db")
cursor = connection.cursor()

### **Creating a table**

In [3]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    age INTEGER
)
""")

## **Topic 2 — Inserting records with execute and parameters**

In [4]:
name = input("Enter your name")
age = int(input("Enter your age"))

cursor.execute(
"INSERT INTO users(name, age) VALUES(?, ?)",
    (name, age) 
)

### **Inserting multiple rows with executemany**

In [5]:
data = (("Ali", 25), ("Selim", 26))

cursor.executemany(
    "INSERT INTO users(name, age) VALUES(?, ?)",
    data)

### **Saving changes**

In [6]:
connection.commit()

## **Topic 3 — Running a SELECT and fetching rows**

In [7]:
cursor.execute("SELECT * FROM users")
# cursor.fetchall()

In [8]:
# cursor.fetchone()
cursor.fetchmany(size = 2)

[(1, '[REDACTED]', '[REDACTED]'), (2, 'Ali', 25)]

### **Printing one row at a time**

In [9]:
for row in cursor.fetchall():
    print(row)

(3, 'Selim', 26)

## **Topic 4 — Filtering rows with SQL parameters**

In [10]:
age_threshold = int(input("Please enter the age threshold: "))

cursor.execute("SELECT * FROM users WHERE age > ?", (age_threshold,))
cursor.fetchall()

[(2, 'Ali', 25), (3, 'Selim', 26)]

## **Topic 5 — Connecting Python to SQL Server**

In [11]:
import pyodbc

### **Connecting Python to SQL Server**

#### **1. `pyodbc.connect()`**

```python
connection = pyodbc.connect(...)
```

`pyodbc.connect()` opens a connection between Python and a database.

The `connection` variable stores the database connection.

---

#### **2. DRIVER**

```python
'DRIVER={ODBC Driver 18 for SQL Server};'
```

Specifies the ODBC driver that Python should use to communicate with SQL Server.

**ODBC** = Open Database Connectivity.

The driver acts as a bridge between `pyodbc` and SQL Server.

---

#### **3. SERVER**

```python
f'SERVER={server};'
```

Specifies the SQL Server instance that Python should connect to.

**Example:**

```python
server = r'DESKTOP-ABC123\SQLEXPRESS'
```

The `f` before the string allows the value of the `server` variable to be inserted into the string.

---

#### **4. DATABASE**

```python
f'DATABASE={database};'
```

Specifies which database on the SQL Server should be used.

**Example:**

```python
database = 'CompanyDB'
```

This tells Python to connect specifically to the `CompanyDB` database.

---

#### **5. Trusted_Connection**

```python
'Trusted_Connection=yes;'
```

Tells the driver to use **Windows Authentication**.

The current Windows user account is used instead of providing a SQL Server username and password in the connection string.

---

#### **6. Encrypt**

```python
'Encrypt=yes;'
```

Requests an encrypted connection between Python and SQL Server.

This helps protect data while it is being transmitted.

---

#### **7. TrustServerCertificate**

```python
'TrustServerCertificate=yes;'
```

Tells the driver to trust the SQL Server's certificate without requiring it to be verified by a trusted certificate authority.

This is commonly useful in local/development environments where SQL Server may use a self-signed certificate.

---

#### **8. Semicolon `;`**

The semicolon separates different connection settings.

**For example:**

```text
DRIVER=...;
SERVER=...;
DATABASE=...;
Encrypt=yes;
```

Each setting is separated by `;`.

---

### **Complete Example Complete Example**

```text
Python
   ↓
pyodbc
   ↓
ODBC Driver 18
   ↓
SQL Server
   ↓
CompanyDB
```

After the connection is established, a cursor can be created:

```python
cursor = connection.cursor()
```

The cursor is then used to execute SQL queries.

In [12]:
server = r'YOUR_SERVER\SQLEXPRESS'
database = 'Online_Course'

connection = pyodbc.connect(
    'DRIVER={ODBC Driver 18 for SQL Server};'
    f'SERVER={server};'
    f'DATABASE={database};'
    'Trusted_Connection=yes;'
    'Encrypt=yes;'
    'TrustServerCertificate=yes;'
)

cursor = connection.cursor()
print("Connected Successfully!")

Connected Successfully!

## **Topic 6 — Listing tables and reading SQL Server data**

In [13]:
cursor.execute("""
SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE'
""")

for row in cursor.fetchall():
    print(row.TABLE_NAME)

Students
Enrollments

### **Reading the Students table**

In [14]:
cursor.execute("SELECT * FROM Students")
cursor.fetchall()

[(1, 'Ahmed', 'Ali', 20, 'Cairo', Decimal('3.40')),
 (2, 'Sara', 'Hassan', 22, 'Alexandria', Decimal('3.80')),
 (3, 'Omar', 'Khaled', 19, 'Cairo', Decimal('2.90')),
 (4, 'Mona', 'Samir', 23, 'Giza', Decimal('3.60')),
 (5, 'Youssef', 'Adel', 21, 'Cairo', Decimal('3.10')),
 (6, 'Nour', 'Mohamed', 24, 'Giza', Decimal('3.90')),
 (7, 'Karim', 'Mostafa', 20, 'Alexandria', Decimal('2.70')),
 (8, 'Laila', 'Tarek', 22, 'Cairo', Decimal('3.50')),
 (9, 'Hany', 'Wael', 25, 'Mansoura', Decimal('2.80')),
 (10, 'Reem', 'Ashraf', 21, 'Giza', Decimal('3.70'))]

## **Topic 7 — Loading query results into pandas**

In [15]:
import pandas as pd

In [16]:
df = pd.read_sql("SELECT * FROM Students", connection)

C:\Users\youmn\AppData\Local\Temp\ipykernel_11460\745162278.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql("SELECT * FROM Students", connection)

In [17]:
df

   StudentID FirstName LastName  Age        City  GPA
0          1     Ahmed      Ali   20       Cairo  3.4
1          2      Sara   Hassan   22  Alexandria  3.8
2          3      Omar   Khaled   19       Cairo  2.9
3          4      Mona    Samir   23        Giza  3.6
4          5   Youssef     Adel   21       Cairo  3.1
5          6      Nour  Mohamed   24        Giza  3.9
6          7     Karim  Mostafa   20  Alexandria  2.7
7          8     Laila    Tarek   22       Cairo  3.5
8          9      Hany     Wael   25    Mansoura  2.8
9         10      Reem   Ashraf   21        Giza  3.7

## **Topic 8 — Joining student and enrollment records**

In [18]:
query = """ 
SELECT s.StudentID, s.FirstName, s.LastName, e.CourseName, e.Grade
FROM Students s 
JOIN Enrollments e 
    ON s.StudentID = e.StudentID
"""

df = pd.read_sql(query, connection)

C:\Users\youmn\AppData\Local\Temp\ipykernel_11460\2068613025.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, connection)

In [19]:
df

    StudentID FirstName LastName   CourseName  Grade
0           1     Ahmed      Ali     Database     85
1           2      Sara   Hassan     Database     95
2           3      Omar   Khaled  Programming     70
3           1     Ahmed      Ali  Programming     90
4           4      Mona    Samir           AI     88
5           5   Youssef     Adel     Database     78
6           6      Nour  Mohamed           AI     97
7           7     Karim  Mostafa  Programming     65
8           8     Laila    Tarek     Database     91
9           2      Sara   Hassan           AI     93
10          9      Hany     Wael     Database     68
11         10      Reem   Ashraf  Programming     89
12          5   Youssef     Adel           AI     82
13          8     Laila    Tarek  Programming     87
14          4      Mona    Samir     Database     84

## **Topic 9 — Filtering and sorting the DataFrame**

In [20]:
df[df["Grade"] > 80]

    StudentID FirstName LastName   CourseName  Grade
0           1     Ahmed      Ali     Database     85
1           2      Sara   Hassan     Database     95
3           1     Ahmed      Ali  Programming     90
4           4      Mona    Samir           AI     88
6           6      Nour  Mohamed           AI     97
8           8     Laila    Tarek     Database     91
9           2      Sara   Hassan           AI     93
11         10      Reem   Ashraf  Programming     89
12          5   Youssef     Adel           AI     82
13          8     Laila    Tarek  Programming     87
14          4      Mona    Samir     Database     84

In [21]:
df.query("Grade > 80")

    StudentID FirstName LastName   CourseName  Grade
0           1     Ahmed      Ali     Database     85
1           2      Sara   Hassan     Database     95
3           1     Ahmed      Ali  Programming     90
4           4      Mona    Samir           AI     88
6           6      Nour  Mohamed           AI     97
8           8     Laila    Tarek     Database     91
9           2      Sara   Hassan           AI     93
11         10      Reem   Ashraf  Programming     89
12          5   Youssef     Adel           AI     82
13          8     Laila    Tarek  Programming     87
14          4      Mona    Samir     Database     84

### **Sorting by grade**

In [22]:
df.sort_values("Grade", ascending=False)

    StudentID FirstName LastName   CourseName  Grade
6           6      Nour  Mohamed           AI     97
1           2      Sara   Hassan     Database     95
9           2      Sara   Hassan           AI     93
8           8     Laila    Tarek     Database     91
3           1     Ahmed      Ali  Programming     90
11         10      Reem   Ashraf  Programming     89
4           4      Mona    Samir           AI     88
13          8     Laila    Tarek  Programming     87
0           1     Ahmed      Ali     Database     85
14          4      Mona    Samir     Database     84
12          5   Youssef     Adel           AI     82
5           5   Youssef     Adel     Database     78
2           3      Omar   Khaled  Programming     70
10          9      Hany     Wael     Database     68
7           7     Karim  Mostafa  Programming     65

## **Topic 10 — Conditional labels with SQL CASE**

#### **Query each student's course and grade, and classify the grade as:**
- Excellent for grades of at least 90.
- Very Good for grades of at least 80.
- Good for grades of at least 70.
- Pass for grades of at least 50.
- Fail otherwise.

In [23]:
query = """
SELECT StudentID, CourseName, Grade,
    CASE 
        WHEN Grade >= 90 THEN 'Excellent'
        WHEN Grade >= 80 THEN 'Very Good'
        WHEN Grade >= 70 THEN 'Good'
        WHEN Grade >= 50 THEN  'Pass'
        ELSE 'Fail'
    END AS GPA
FROM Enrollments
"""

pd.read_sql(query, connection)

C:\Users\youmn\AppData\Local\Temp\ipykernel_11460\3627190066.py:13: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, connection)

    StudentID   CourseName  Grade        GPA
0           1     Database     85  Very Good
1           2     Database     95  Excellent
2           3  Programming     70       Good
3           1  Programming     90  Excellent
4           4           AI     88  Very Good
5           5     Database     78       Good
6           6           AI     97  Excellent
7           7  Programming     65       Pass
8           8     Database     91  Excellent
9           2           AI     93  Excellent
10          9     Database     68       Pass
11         10  Programming     89  Very Good
12          5           AI     82  Very Good
13          8  Programming     87  Very Good
14          4     Database     84  Very Good

## **Topic 11 — Joining data and classifying pass or fail**

In [24]:
query = """ 
SELECT s.StudentID, 
s.FirstName,
s.LastName,
e.CourseName,
e.Grade,
CASE
    WHEN e.Grade >= 50 THEN 'Passed'
    ELSE 'Failed'
END AS Result
FROM Students s
JOIN Enrollments e
    ON s.StudentID = e.StudentID
"""
pd.read_sql(query, connection)

C:\Users\youmn\AppData\Local\Temp\ipykernel_11460\589581657.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, connection)

    StudentID FirstName LastName   CourseName  Grade  Result
0           1     Ahmed      Ali     Database     85  Passed
1           2      Sara   Hassan     Database     95  Passed
2           3      Omar   Khaled  Programming     70  Passed
3           1     Ahmed      Ali  Programming     90  Passed
4           4      Mona    Samir           AI     88  Passed
5           5   Youssef     Adel     Database     78  Passed
6           6      Nour  Mohamed           AI     97  Passed
7           7     Karim  Mostafa  Programming     65  Passed
8           8     Laila    Tarek     Database     91  Passed
9           2      Sara   Hassan           AI     93  Passed
10          9      Hany     Wael     Database     68  Passed
11         10      Reem   Ashraf  Programming     89  Passed
12          5   Youssef     Adel           AI     82  Passed
13          8     Laila    Tarek  Programming     87  Passed
14          4      Mona    Samir     Database     84  Passed

## **Topic 12 — Running SQL directly in a notebook**

In [25]:
%pip install ipython-sql

Requirement already satisfied: ipython-sql in c:\Users\youmn\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (0.5.0)
Requirement already satisfied: prettytable in c:\Users\youmn\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from ipython-sql) (3.18.0)
Requirement already satisfied: ipython in C:\Users\youmn\AppData\Roaming\Python\Python314\site-packages (from ipython-sql) (9.17.1)
Requirement already satisfied: sqlalchemy>=2.0 in c:\Users\youmn\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from ipython-sql) (2.1.3)
Requirement already satisfied: sqlparse in c:\Users\youmn\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from ipython-sql) (0.6.0)
Requirement already satisfied: six in C:\Users\youmn\AppData\Roaming\Python\Python314\site-packages (from ipython-sql) (1.17.0)
Requirement already satisfied: ipython-genutils in c:\Users\youmn\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\youmn\AppData\Roaming\Python\Python314\site-packages (from sqlalchemy>=2.0->ipython-sql) (4.16.0)
Requirement already satisfied: colorama>=0.4.4 in C:\Users\youmn\AppData\Roaming\Python\Python314\site-packages (from ipython->ipython-sql) (0.4.6)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in C:\Users\youmn\AppData\Roaming\Python\Python314\site-packages (from ipython->ipython-sql) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in C:\Users\youmn\AppData\Roaming\Python\Python314\site-packages (from ipython->ipython-sql) (0.20.0)
Requirement already satisfied: matplotlib-inline>=0.1.6 in C:\Users\youmn\AppData\Roaming\Python\Python314\site-packages (from ipython->ipython-sql) (0.2.2)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in C:\Users\youmn\AppData\Roaming\Python\Python314\site-packages (from ipython->ipython-sql) (3.0.53)
Requirement already satisfied: psutil>=7 in C:\Users\youmn\AppData\Roaming\Python\Python314\site-packages (from ipython->ipython-sql) (7.2.2)
Requirement already satisfied: pygments>=2.14.0 in C:\Users\youmn\AppData\Roaming\Python\Python314\site-packages (from ipython->ipython-sql) (2.21.0)
Requirement already satisfied: stack_data>=0.6.0 in C:\Users\youmn\AppData\Roaming\Python\Python314\site-packages (from ipython->ipython-sql) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in C:\Users\youmn\AppData\Roaming\Python\Python314\site-packages (from ipython->ipython-sql) (5.16.1)
Requirement already satisfied: wcwidth>=0.1.4 in C:\Users\youmn\AppData\Roaming\Python\Python314\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython->ipython-sql) (0.8.4)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in C:\Users\youmn\AppData\Roaming\Python\Python314\site-packages (from jedi>=0.18.2->ipython->ipython-sql) (0.8.7)
Requirement already satisfied: executing>=1.2.0 in C:\Users\youmn\AppData\Roaming\Python\Python314\site-packages (from stack_data>=0.6.0->ipython->ipython-sql) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in C:\Users\youmn\AppData\Roaming\Python\Python314\site-packages (from stack_data>=0.6.0->ipython->ipython-sql) (3.0.2)
Requirement already satisfied: pure-eval in C:\Users\youmn\AppData\Roaming\Python\Python314\site-packages (from stack_data>=0.6.0->ipython->ipython-sql) (0.2.4)
Note: you may need to restart the kernel to use updated packages.

In [26]:
%load_ext sql
%sql sqlite3:///Online_Course.db

Traceback (most recent call last):
  File "c:\Users\youmn\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sql\connection.py", line 45, in __init__
    engine = sqlalchemy.create_engine(
        connect_str, connect_args=connect_args
    )
  File "<sqlalchemy generated warned() wrapper for sqlalchemy.engine.create.create_engine>", line 2, in create_engine
    return target(fn, url, **kwargs)
  File "c:\Users\youmn\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sqlalchemy\util\deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "c:\Users\youmn\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sqlalchemy\engine\create.py", line 553, in create_engine
    entrypoint = u._get_entrypoint()
  File "c:\Users\youmn\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sqlalchemy\engine\url.py", line 772, in _get_entrypoint
    cls = registry.load(name)
  File "c:\Users\youmn\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 501, in load
    raise exc.NoSuchModuleError(
        "Can't load plugin: %s:%s" % (self.group, name)
    )
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:sqlite3

Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys([])
Traceback (most recent call last):
  File "c:\Users\youmn\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sql\magic.py", line 196, in execute
    conn = sql.connection.Connection.set(
        connect_str,
    ...<2 lines>...
        creator=args.creator,
    )
  File "c:\Users\youmn\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sql\connection.py", line 70, in set
    cls.current = existing or Connection(descriptor, connect_args, creator)
                              ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\youmn\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sql\connection.py", line 45, in __init__
    engine = sqlalchemy.create_engine(
        connect_str, connect_args=connect_args
    )
  File "<sqlalchemy generated warned() wrapper for sqlalchemy.engine.create.create_engine>", line 2, in create_engine
    return target(fn, url, **kwargs)
  File "c:\Users\youmn\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sqlalchemy\util\deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "c:\Users\youmn\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sqlalchemy\engine\create.py", line 553, in create_engine
    entrypoint = u._get_entrypoint()
  File "c:\Users\youmn\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sqlalchemy\engine\url.py", line 772, in _get_entrypoint
    cls = registry.load(name)
  File "c:\Users\youmn\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 501, in load
    raise exc.NoSuchModuleError(
        "Can't load plugin: %s:%s" % (self.group, name)
    )
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:sqlite3

Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys([])

In [27]:
%%sql
SELECT * FROM users;

Traceback (most recent call last):
  File "c:\Users\youmn\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sql\magic.py", line 196, in execute
    conn = sql.connection.Connection.set(
        connect_str,
    ...<2 lines>...
        creator=args.creator,
    )
  File "c:\Users\youmn\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sql\connection.py", line 82, in set
    raise ConnectionError(
        "Environment variable $DATABASE_URL not set, and no connect string given."
    )
sql.connection.ConnectionError: Environment variable $DATABASE_URL not set, and no connect string given.

Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys([])